spring.datasource.url=jdbc:mysql://localhost:3306/LibraryDB?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=080708
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 讓 Spring Boot 啟動時在 8080 port
server.port=8080
